#!/bin/bash

# This bash script refreshes our local copy of Scott Vokes'
# (silentbicycle's) Lunatest script.
#
# For our purposes, we ONLY need the lunatest.lua script itself.

wget \
 -O t-contests/tex/context/third/ConTests/t-contests-lunatest.lua \
 https://raw.githubusercontent.com/silentbicycle/lunatest/master/lunatest.lua
